config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root to: 'welcome#index'

  resources :entregas  
  resources :cardapios
  resources :pedidos
  resources :clientes
  

end

app/models/entrega.rb
class Entrega < ActiveRecord::Base
  belongs_to :Pedido
end

app/controllers/entregas_controller.rb
class EntregasController < ApplicationController
  before_action :set_entrega, only: [:show, :edit, :update, :destroy]

  # GET /entregas
  # GET /entregas.json
  def index
    @entregas = Entrega.all
  end

  # GET /entregas/1
  # GET /entregas/1.json
  def show
  end

  # GET /entregas/new
  def new
    @entrega = Entrega.new
  end

  # GET /entregas/1/edit
  def edit
  end

  # POST /entregas
  # POST /entregas.json
  def create
    @entrega = Entrega.new(entrega_params)

    respond_to do |format|
      if @entrega.save
        format.html { redirect_to @entrega, notice: 'Entrega was successfully created.' }
        format.json { render :show, status: :created, location: @entrega }
      else
        format.html { render :new }
        format.json { render json: @entrega.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entregas/1
  # PATCH/PUT /entregas/1.json
  def update
    respond_to do |format|
      if @entrega.update(entrega_params)
        format.html { redirect_to @entrega, notice: 'Entrega was successfully updated.' }
        format.json { render :show, status: :ok, location: @entrega }
      else
        format.html { render :edit }
        format.json { render json: @entrega.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entregas/1
  # DELETE /entregas/1.json
  def destroy
    @entrega.destroy
    respond_to do |format|
      format.html { redirect_to entregas_url, notice: 'Entrega was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entrega
      @entrega = Entrega.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entrega_params
      params.require(:entrega).permit(:data, :situacao, :Pedido_id)
    end
end

app/helpers/entregas_helper.rb
module EntregasHelper
end

app/views/entregas/_form.html.haml
= simple_form_for(@entrega) do |f|
  = f.error_notification

  .form-inputs
    = f.input :data
    = f.input :situacao, label: "situação"
    = f.association :Pedido
    f.input :nome
    

  .form-actions
    = f.submit "Salvar"

app/views/entregas/edit.html.haml
%h1 Editing entrega

= render 'form'

= link_to 'Mostrar', @entrega
\|
= link_to 'Voltar', entregas_path

app/views/entregas/index.html.haml
%h1 Listing entregas

%table
  %thead
    %tr
      %th Data
      %th Situacao
      %th Pedido
      %th
      %th
      %th

  %tbody
    - @entregas.each do |entrega|
      %tr
        %td= entrega.data
        %td= entrega.situacao
        %td= entrega.Pedido
        %td= link_to 'Mostrar', entrega
        %td= link_to 'Editar', edit_entrega_path(entrega)
        %td= link_to 'Excluir', entrega, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Nova Entrega', new_entrega_path

app/views/entregas/new.html.haml
%h1 New entrega

= render 'form'

= link_to 'Voltar', entregas_path

app/views/entregas/show.html.haml
%p#notice= notice

%p
  %b Data:
  = @entrega.data
%p
  %b Situacao:
  = @entrega.situacao
%p
  %b Pedido:
  = @entrega.Pedido

= link_to 'Editar', edit_entrega_path(@entrega)
\|
= link_to 'Voltar', entregas_path