config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root to: 'welcome#index'

  resources :entregas  
  resources :cardapios
  resources :pedidos
  resources :clientes
  

end

app/models/cardapio.rb
class Cardapio < ActiveRecord::Base
end

app/controllers/cardapios_controller.rb
class CardapiosController < ApplicationController
  before_action :set_cardapio, only: [:show, :edit, :update, :destroy]

  # GET /cardapios
  # GET /cardapios.json
  def index
    @cardapios = Cardapio.all
  end

  # GET /cardapios/1
  # GET /cardapios/1.json
  def show
  end

  # GET /cardapios/new
  def new
    @cardapio = Cardapio.new
  end

  # GET /cardapios/1/edit
  def edit
  end

  # POST /cardapios
  # POST /cardapios.json
  def create
    @cardapio = Cardapio.new(cardapio_params)

    respond_to do |format|
      if @cardapio.save
        format.html { redirect_to @cardapio, notice: 'Cardapio was successfully created.' }
        format.json { render :show, status: :created, location: @cardapio }
      else
        format.html { render :new }
        format.json { render json: @cardapio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cardapios/1
  # PATCH/PUT /cardapios/1.json
  def update
    respond_to do |format|
      if @cardapio.update(cardapio_params)
        format.html { redirect_to @cardapio, notice: 'Cardapio was successfully updated.' }
        format.json { render :show, status: :ok, location: @cardapio }
      else
        format.html { render :edit }
        format.json { render json: @cardapio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cardapios/1
  # DELETE /cardapios/1.json
  def destroy
    @cardapio.destroy
    respond_to do |format|
      format.html { redirect_to cardapios_url, notice: 'Cardapio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cardapio
      @cardapio = Cardapio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cardapio_params
      params.require(:cardapio).permit(:nome, :descricao, :preco)
    end
end

app/helpers/cardapios_helper.rb
module CardapiosHelper
end

app/views/cardapios/_form.html.haml
= simple_form_for(@cardapio) do |f|
  = f.error_notification

  .form-inputs
    = f.input :nome
    = f.input :descricao, label: "Descrição"
    = f.input :preco, label: "Preço"

  .form-actions
    = f.submit "Salvar"

app/views/cardapios/edit.html.haml
%h1 Editing cardapio

= render 'form'

= link_to 'Show', @cardapio
\|
= link_to 'Back', cardapios_path

app/views/cardapios/index.html.haml
%h1 Lista de Cardapio

%table
  %thead
    %tr
      %th Nome
      %th Descricao
      %th Preco
      %th
      %th
      %th

  %tbody
    - @cardapios.each do |cardapio|
      %tr
        %td= cardapio.nome
        %td= cardapio.descricao
        %td= cardapio.preco
        %td= link_to 'Mostrar', cardapio
        %td= link_to 'Editar', edit_cardapio_path(cardapio)
        %td= link_to 'Excluir', cardapio, :method => :delete, :data => { :confirm => 'Are you sure?' }

      

%br

= link_to 'Novo Cardapio', new_cardapio_path

app/views/cardapios/new.html.haml
%h1 New cardapio

= render 'form'

= link_to 'Back', cardapios_path

app/views/cardapios/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @cardapio.nome
%p
  %b Descrição:
  = @cardapio.descricao
%p
  %b Preço:
  = @cardapio.preco

= link_to 'Edit', edit_cardapio_path(@cardapio)
\|
= link_to 'Back', cardapios_path